spring:
  application:
    name: clinicalsapi
  datasource:
    url: jdbc:mysql://localhost:3306/clinicals
    username: root
    password: password

server:
  servlet:
    context-path: /clinicalservices

logging:
  level:
    root: INFO
    jayslabs.copilot.clinicalsapi.controller.PatientController: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log