spring:
  application:
    name: flightreservation
  datasource:
    url: jdbc:mysql://localhost:3306/RESERVATION
    username: root
    password: password
  jpa:
    show-sql: true

server:
  servlet:
    context-path: /flightreservation

logging:
  level:
    root: INFO
    jayslabs.copilot.flightreservation.controller.*: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/application.log